import { generateId } from './utils';
import type {
  User,
  Region,
  Warehouse,
  Rack,
  ComponentType,
  InventoryItem,
  Component,
  InventoryRequest,
  InstallRequest,
  RelocationRequest,
  Customer,
  Vendor,
  AuditLog,
  Notification,
  ReservedStock,
  MaintenanceTask,
  PurchaseOrder,
  GoodsReceipt,
  RMARecord,
  DisposalRecord,
  StocktakeRecord } from
'./types';

const now = new Date().toISOString();
const d = (daysAgo: number) =>
new Date(Date.now() - daysAgo * 86400000).toISOString();

// ---- REGIONS ----
export const mockRegions: Region[] = [
{
  id: 'r1',
  name: 'Yangon',
  description: 'Yangon Region — Main operations hub',
  is_active: true,
  created_at: d(365),
  updated_at: d(30)
},
{
  id: 'r2',
  name: 'Mandalay',
  description: 'Mandalay Region — Northern operations',
  is_active: true,
  created_at: d(365),
  updated_at: d(60)
},
{
  id: 'r3',
  name: 'Naypyidaw',
  description: 'Naypyidaw Region — Government sector',
  is_active: true,
  created_at: d(300),
  updated_at: d(90)
},
{
  id: 'r4',
  name: 'Bago',
  description: 'Bago Region — Eastern operations',
  is_active: true,
  created_at: d(200),
  updated_at: d(45)
}];


// ---- WAREHOUSES ----
export const mockWarehouses: Warehouse[] = [
{
  id: 'w1',
  name: 'Ahlone DC',
  region_id: 'r1',
  address: '123 Ahlone Road, Yangon',
  contact_person: 'U Kyaw Zin',
  contact_phone: '+95-9-123456789',
  is_active: true,
  created_at: d(365),
  updated_at: d(10)
},
{
  id: 'w2',
  name: 'Hlaing DC',
  region_id: 'r1',
  address: '456 Hlaing Township, Yangon',
  contact_person: 'Daw Aye Aye',
  contact_phone: '+95-9-987654321',
  is_active: true,
  created_at: d(300),
  updated_at: d(20)
},
{
  id: 'w3',
  name: 'Mandalay DC',
  region_id: 'r2',
  address: '789 73rd Street, Mandalay',
  contact_person: 'U Myo Thant',
  contact_phone: '+95-9-555666777',
  is_active: true,
  created_at: d(300),
  updated_at: d(15)
},
{
  id: 'w4',
  name: 'Naypyidaw DC',
  region_id: 'r3',
  address: '101 Ministry Road, Naypyidaw',
  contact_person: 'U Zaw Win',
  contact_phone: '+95-9-111222333',
  is_active: true,
  created_at: d(250),
  updated_at: d(30)
},
{
  id: 'w5',
  name: 'Bago Warehouse',
  region_id: 'r4',
  address: '55 Bago Main St',
  contact_person: 'U Hla Tun',
  contact_phone: '+95-9-444555666',
  is_active: true,
  created_at: d(180),
  updated_at: d(25)
}];


// ---- RACKS ----
export const mockRacks: Rack[] = [
{
  id: 'rk1',
  name: 'Rack-A01',
  warehouse_id: 'w1',
  location: 'Floor 1, Room 101',
  total_units: 42,
  used_units: 28,
  is_active: true,
  created_at: d(300),
  updated_at: d(5)
},
{
  id: 'rk2',
  name: 'Rack-A02',
  warehouse_id: 'w1',
  location: 'Floor 1, Room 101',
  total_units: 42,
  used_units: 35,
  is_active: true,
  created_at: d(300),
  updated_at: d(3)
},
{
  id: 'rk3',
  name: 'Rack-B01',
  warehouse_id: 'w1',
  location: 'Floor 2, Room 201',
  total_units: 42,
  used_units: 12,
  is_active: true,
  created_at: d(250),
  updated_at: d(7)
},
{
  id: 'rk4',
  name: 'Rack-C01',
  warehouse_id: 'w2',
  location: 'Floor 1, Room A',
  total_units: 42,
  used_units: 20,
  is_active: true,
  created_at: d(250),
  updated_at: d(10)
},
{
  id: 'rk5',
  name: 'Rack-M01',
  warehouse_id: 'w3',
  location: 'Floor 1, Main Hall',
  total_units: 42,
  used_units: 18,
  is_active: true,
  created_at: d(200),
  updated_at: d(12)
},
{
  id: 'rk6',
  name: 'Rack-N01',
  warehouse_id: 'w4',
  location: 'Floor 1, Server Room',
  total_units: 42,
  used_units: 8,
  is_active: true,
  created_at: d(200),
  updated_at: d(15)
}];


// ---- USERS ----
export const mockUsers: User[] = [
{
  id: 'u1',
  username: 'admin',
  email: 'admin@1cng.com',
  password_hash: 'admin123',
  full_name: 'U Aung Ko Ko',
  role: 'Admin',
  assigned_region_id: null,
  assigned_warehouse_id: null,
  is_active: true,
  last_login: d(0),
  created_at: d(365),
  updated_at: d(0)
},
{
  id: 'u2',
  username: 'pm_yangon',
  email: 'pm.yangon@1cng.com',
  password_hash: 'pm123',
  full_name: 'Daw Su Su Hlaing',
  role: 'PM',
  assigned_region_id: 'r1',
  assigned_warehouse_id: 'w1',
  is_active: true,
  last_login: d(0),
  created_at: d(300),
  updated_at: d(1)
},
{
  id: 'u3',
  username: 'pm_mandalay',
  email: 'pm.mdy@1cng.com',
  password_hash: 'pm123',
  full_name: 'U Zaw Min Oo',
  role: 'PM',
  assigned_region_id: 'r2',
  assigned_warehouse_id: 'w3',
  is_active: true,
  last_login: d(1),
  created_at: d(280),
  updated_at: d(2)
},
{
  id: 'u4',
  username: 'eng_kaung',
  email: 'kaung@1cng.com',
  password_hash: 'eng123',
  full_name: 'Mg Kaung Myat',
  role: 'Engineer',
  assigned_region_id: 'r1',
  assigned_warehouse_id: 'w1',
  is_active: true,
  last_login: d(0),
  created_at: d(200),
  updated_at: d(0)
},
{
  id: 'u5',
  username: 'eng_thura',
  email: 'thura@1cng.com',
  password_hash: 'eng123',
  full_name: 'Mg Thura Aung',
  role: 'Engineer',
  assigned_region_id: 'r1',
  assigned_warehouse_id: 'w2',
  is_active: true,
  last_login: d(0),
  created_at: d(180),
  updated_at: d(1)
},
{
  id: 'u6',
  username: 'eng_mdy',
  email: 'htet@1cng.com',
  password_hash: 'eng123',
  full_name: 'Mg Htet Aung',
  role: 'Engineer',
  assigned_region_id: 'r2',
  assigned_warehouse_id: 'w3',
  is_active: true,
  last_login: d(2),
  created_at: d(150),
  updated_at: d(3)
},
{
  id: 'u7',
  username: 'newuser',
  email: 'new@1cng.com',
  password_hash: 'new123',
  full_name: 'Ma Aye Chan',
  role: 'Engineer',
  assigned_region_id: null,
  assigned_warehouse_id: null,
  is_active: true,
  last_login: null,
  created_at: d(5),
  updated_at: d(5)
}];


// ---- COMPONENT TYPES ----
export const mockComponentTypes: ComponentType[] = [
{
  id: 'ct1',
  type_name: 'RAM',
  category: 'Hardware',
  description: 'Random Access Memory modules',
  requires_specification: true,
  is_active: true,
  created_by: 'u1',
  created_at: d(365),
  updated_at: d(30)
},
{
  id: 'ct2',
  type_name: 'SSD',
  category: 'Hardware',
  description: 'Solid State Drives',
  requires_specification: true,
  is_active: true,
  created_by: 'u1',
  created_at: d(365),
  updated_at: d(30)
},
{
  id: 'ct3',
  type_name: 'HDD',
  category: 'Hardware',
  description: 'Hard Disk Drives',
  requires_specification: true,
  is_active: true,
  created_by: 'u1',
  created_at: d(365),
  updated_at: d(30)
},
{
  id: 'ct4',
  type_name: 'CPU',
  category: 'Hardware',
  description: 'Central Processing Units',
  requires_specification: true,
  is_active: true,
  created_by: 'u1',
  created_at: d(365),
  updated_at: d(30)
},
{
  id: 'ct5',
  type_name: 'NIC',
  category: 'Hardware',
  description: 'Network Interface Cards',
  requires_specification: true,
  is_active: true,
  created_by: 'u1',
  created_at: d(365),
  updated_at: d(30)
},
{
  id: 'ct6',
  type_name: 'PSU',
  category: 'Hardware',
  description: 'Power Supply Units',
  requires_specification: true,
  is_active: true,
  created_by: 'u1',
  created_at: d(365),
  updated_at: d(30)
},
{
  id: 'ct7',
  type_name: 'GPU',
  category: 'Hardware',
  description: 'Graphics Processing Units',
  requires_specification: true,
  is_active: true,
  created_by: 'u1',
  created_at: d(365),
  updated_at: d(30)
},
{
  id: 'ct8',
  type_name: 'Fan',
  category: 'Hardware',
  description: 'Cooling fans',
  requires_specification: false,
  is_active: true,
  created_by: 'u1',
  created_at: d(365),
  updated_at: d(30)
},
{
  id: 'ct9',
  type_name: 'Motherboard',
  category: 'Hardware',
  description: 'Server motherboards',
  requires_specification: true,
  is_active: true,
  created_by: 'u1',
  created_at: d(300),
  updated_at: d(30)
},
{
  id: 'ct10',
  type_name: 'Cable',
  category: 'Accessory',
  description: 'Various cables',
  requires_specification: false,
  is_active: true,
  created_by: 'u1',
  created_at: d(365),
  updated_at: d(30)
},
{
  id: 'ct11',
  type_name: 'Transceiver',
  category: 'Hardware',
  description: 'SFP/QSFP transceivers',
  requires_specification: true,
  is_active: true,
  created_by: 'u1',
  created_at: d(300),
  updated_at: d(30)
},
{
  id: 'ct12',
  type_name: 'Rail Kit',
  category: 'Accessory',
  description: 'Server rail kits',
  requires_specification: false,
  is_active: true,
  created_by: 'u1',
  created_at: d(300),
  updated_at: d(30)
},
{
  id: 'ct13',
  type_name: 'RAID Controller',
  category: 'Hardware',
  description: 'RAID controller cards',
  requires_specification: true,
  is_active: true,
  created_by: 'u1',
  created_at: d(300),
  updated_at: d(30)
},
{
  id: 'ct14',
  type_name: 'HBA',
  category: 'Hardware',
  description: 'Host Bus Adapters',
  requires_specification: true,
  is_active: true,
  created_by: 'u1',
  created_at: d(300),
  updated_at: d(30)
},
{
  id: 'ct15',
  type_name: 'Heatsink',
  category: 'Hardware',
  description: 'CPU heatsinks',
  requires_specification: false,
  is_active: true,
  created_by: 'u1',
  created_at: d(250),
  updated_at: d(30)
},
{
  id: 'ct16',
  type_name: 'NVMe',
  category: 'Hardware',
  description: 'NVMe drives',
  requires_specification: true,
  is_active: true,
  created_by: 'u1',
  created_at: d(250),
  updated_at: d(30)
},
{
  id: 'ct17',
  type_name: 'Bracket',
  category: 'Accessory',
  description: 'Mounting brackets',
  requires_specification: false,
  is_active: true,
  created_by: 'u1',
  created_at: d(200),
  updated_at: d(30)
},
{
  id: 'ct18',
  type_name: 'Battery',
  category: 'Hardware',
  description: 'RAID BBU, CMOS batteries',
  requires_specification: false,
  is_active: true,
  created_by: 'u1',
  created_at: d(200),
  updated_at: d(30)
},
{
  id: 'ct19',
  type_name: 'Backplane',
  category: 'Hardware',
  description: 'Drive backplanes',
  requires_specification: true,
  is_active: true,
  created_by: 'u1',
  created_at: d(200),
  updated_at: d(30)
},
{
  id: 'ct20',
  type_name: 'Controller Card',
  category: 'Hardware',
  description: 'Various controller cards',
  requires_specification: true,
  is_active: true,
  created_by: 'u1',
  created_at: d(200),
  updated_at: d(30)
}];


// ---- INVENTORY ITEMS ----
export const mockInventory: InventoryItem[] = [
{
  id: 'inv1',
  item_name: 'Dell PowerEdge R750',
  item_type: 'Server',
  manufacturer: 'Dell',
  model: 'PowerEdge R750',
  serial_number: 'SRV-DELL-R750-001',
  asset_tag: 'AT-001',
  specifications: {
    form_factor: '2U',
    cpu_model: 'Intel Xeon Gold 6348',
    cpu_count: 2,
    cores_per_cpu: 28,
    ram_type: 'DDR4',
    ram_speed: '3200MHz',
    total_ram_gb: 256,
    storage_bays: 24,
    total_storage_tb: 12,
    network_ports: 4,
    port_speed: '25GbE',
    psu_count: 2,
    psu_wattage: 1400
  },
  region_id: 'r1',
  warehouse_id: 'w1',
  rack_id: 'rk1',
  rack_position: 'U1-U2',
  floor: 'Floor 1',
  room: 'Room 101',
  cabinet: 'CAB-A',
  network_config: {
    primary_ip: '10.0.1.10',
    hostname: 'srv-ygn-001',
    vlan: '100'
  },
  ownership: { owned_by: 'Company Owned' },
  quantity: 1,
  reserved_quantity: 0,
  status: 'Working',
  condition: 'New',
  lifecycle: { deployment_date: d(90) },
  maintenance: { schedule: 'Quarterly', last_date: d(30) },
  notes: 'Primary production server',
  tags: ['Production', 'Mission Critical'],
  purchase_date: d(120),
  purchase_price: 15000,
  vendor: 'Dell Technologies',
  warranty_expiry_date: d(-730),
  created_by: 'u1',
  created_at: d(120),
  updated_at: d(5),
  updated_by: 'u1',
  is_deleted: false
},
{
  id: 'inv2',
  item_name: 'Dell PowerEdge R650',
  item_type: 'Server',
  manufacturer: 'Dell',
  model: 'PowerEdge R650',
  serial_number: 'SRV-DELL-R650-001',
  asset_tag: 'AT-002',
  specifications: {
    form_factor: '1U',
    cpu_model: 'Intel Xeon Silver 4314',
    cpu_count: 2,
    cores_per_cpu: 16,
    ram_type: 'DDR4',
    ram_speed: '2666MHz',
    total_ram_gb: 128,
    storage_bays: 10,
    total_storage_tb: 4,
    network_ports: 2,
    port_speed: '10GbE',
    psu_count: 2,
    psu_wattage: 800
  },
  region_id: 'r1',
  warehouse_id: 'w1',
  rack_id: 'rk1',
  rack_position: 'U3',
  floor: 'Floor 1',
  room: 'Room 101',
  cabinet: 'CAB-A',
  network_config: { primary_ip: '10.0.1.11', hostname: 'srv-ygn-002' },
  ownership: { owned_by: 'Company Owned' },
  quantity: 1,
  reserved_quantity: 0,
  status: 'Working',
  condition: 'Used',
  lifecycle: { deployment_date: d(200) },
  maintenance: { schedule: 'Quarterly' },
  notes: 'Backup server',
  tags: ['Backup'],
  purchase_date: d(400),
  purchase_price: 9500,
  vendor: 'Dell Technologies',
  warranty_expiry_date: d(30),
  created_by: 'u1',
  created_at: d(400),
  updated_at: d(10),
  updated_by: 'u1',
  is_deleted: false
},
{
  id: 'inv3',
  item_name: 'Cisco Catalyst 9300-48P',
  item_type: 'Switch',
  manufacturer: 'Cisco',
  model: 'Catalyst 9300-48P',
  serial_number: 'SW-CISCO-9300-001',
  asset_tag: 'AT-003',
  specifications: {
    switch_type: 'L3 Managed',
    total_ports: 48,
    port_configuration: '48x 1GbE PoE+ + 4x 10GbE SFP+',
    copper_ports: 48,
    sfp_plus_ports: 4,
    poe_support: 'PoE+',
    poe_budget: 740,
    switching_capacity: 176,
    stackable: true
  },
  region_id: 'r1',
  warehouse_id: 'w1',
  rack_id: 'rk1',
  rack_position: 'U5',
  floor: 'Floor 1',
  room: 'Room 101',
  cabinet: 'CAB-A',
  network_config: {
    primary_ip: '10.0.1.1',
    hostname: 'sw-ygn-core-01',
    vlan: '1'
  },
  ownership: { owned_by: 'Company Owned' },
  quantity: 1,
  reserved_quantity: 0,
  status: 'Working',
  condition: 'New',
  lifecycle: {},
  maintenance: { schedule: 'Semi-Annual' },
  notes: 'Core switch for Ahlone DC',
  tags: ['Core', 'Network'],
  purchase_date: d(180),
  purchase_price: 8500,
  vendor: 'Cisco',
  warranty_expiry_date: d(-365),
  created_by: 'u1',
  created_at: d(180),
  updated_at: d(15),
  updated_by: 'u1',
  is_deleted: false
},
{
  id: 'inv4',
  item_name: 'Juniper MX204',
  item_type: 'Router',
  manufacturer: 'Juniper',
  model: 'MX204',
  serial_number: 'RTR-JNP-MX204-001',
  asset_tag: 'AT-004',
  specifications: {
    router_type: 'Edge',
    throughput: '400 Gbps',
    wan_ports: 4,
    wan_port_speed: '100GbE',
    routing_protocols: ['OSPF', 'BGP', 'IS-IS'],
    vpn_support: ['IPsec']
  },
  region_id: 'r1',
  warehouse_id: 'w1',
  rack_id: 'rk2',
  rack_position: 'U1',
  floor: 'Floor 1',
  room: 'Room 101',
  cabinet: 'CAB-B',
  network_config: { primary_ip: '10.0.0.1', hostname: 'rtr-ygn-edge-01' },
  ownership: { owned_by: 'Company Owned' },
  quantity: 1,
  reserved_quantity: 0,
  status: 'Working',
  condition: 'New',
  lifecycle: {},
  maintenance: { schedule: 'Quarterly' },
  notes: 'Edge router',
  tags: ['Edge', 'Network'],
  purchase_date: d(150),
  purchase_price: 22000,
  vendor: 'Juniper Networks',
  warranty_expiry_date: d(-500),
  created_by: 'u1',
  created_at: d(150),
  updated_at: d(20),
  updated_by: 'u1',
  is_deleted: false
},
{
  id: 'inv5',
  item_name: 'Palo Alto PA-3260',
  item_type: 'Firewall',
  manufacturer: 'Palo Alto',
  model: 'PA-3260',
  serial_number: 'FW-PA-3260-001',
  asset_tag: 'AT-005',
  specifications: {
    firewall_type: 'Next-Gen',
    throughput: '8.7 Gbps',
    max_connections: 2000000,
    network_ports: 12,
    features: [
    'IPS',
    'IDS',
    'DPI',
    'Application Control',
    'URL Filtering',
    'VPN',
    'SSL Inspection'],

    ha: true,
    ha_mode: 'Active-Passive'
  },
  region_id: 'r1',
  warehouse_id: 'w1',
  rack_id: 'rk2',
  rack_position: 'U3',
  floor: 'Floor 1',
  room: 'Room 101',
  cabinet: 'CAB-B',
  network_config: { primary_ip: '10.0.0.2', hostname: 'fw-ygn-01' },
  ownership: { owned_by: 'Company Owned' },
  quantity: 1,
  reserved_quantity: 0,
  status: 'Working',
  condition: 'New',
  lifecycle: {},
  maintenance: { schedule: 'Monthly' },
  notes: 'Primary firewall',
  tags: ['Security', 'Mission Critical'],
  purchase_date: d(160),
  purchase_price: 35000,
  vendor: 'Palo Alto Networks',
  warranty_expiry_date: d(-600),
  created_by: 'u1',
  created_at: d(160),
  updated_at: d(8),
  updated_by: 'u1',
  is_deleted: false
},
{
  id: 'inv6',
  item_name: 'NetApp FAS2750',
  item_type: 'Storage Array',
  manufacturer: 'NetApp',
  model: 'FAS2750',
  serial_number: 'STO-NA-2750-001',
  asset_tag: 'AT-006',
  specifications: {
    storage_type: 'Unified',
    protocol: ['iSCSI', 'NFS', 'SMB'],
    controller_count: 2,
    drive_bays: 24,
    total_raw_capacity_tb: 48,
    raid_levels: ['RAID 6', 'RAID 10'],
    snapshot_support: true,
    replication_support: true,
    deduplication_support: true
  },
  region_id: 'r1',
  warehouse_id: 'w1',
  rack_id: 'rk2',
  rack_position: 'U5-U8',
  floor: 'Floor 1',
  room: 'Room 101',
  cabinet: 'CAB-B',
  network_config: { primary_ip: '10.0.2.10', hostname: 'nas-ygn-01' },
  ownership: { owned_by: 'Company Owned' },
  quantity: 1,
  reserved_quantity: 0,
  status: 'Working',
  condition: 'New',
  lifecycle: {},
  maintenance: { schedule: 'Quarterly' },
  notes: 'Primary storage array',
  tags: ['Storage', 'Production'],
  purchase_date: d(140),
  purchase_price: 45000,
  vendor: 'NetApp',
  warranty_expiry_date: d(-700),
  created_by: 'u1',
  created_at: d(140),
  updated_at: d(12),
  updated_by: 'u1',
  is_deleted: false
},
{
  id: 'inv7',
  item_name: 'HP ProLiant DL380 Gen10',
  item_type: 'Server',
  manufacturer: 'HP',
  model: 'ProLiant DL380 Gen10',
  serial_number: 'SRV-HP-DL380-001',
  asset_tag: 'AT-007',
  specifications: {
    form_factor: '2U',
    cpu_model: 'Intel Xeon Gold 5218',
    cpu_count: 2,
    cores_per_cpu: 16,
    total_ram_gb: 192,
    storage_bays: 8,
    total_storage_tb: 8,
    psu_count: 2,
    psu_wattage: 800
  },
  region_id: 'r2',
  warehouse_id: 'w3',
  rack_id: 'rk5',
  rack_position: 'U1-U2',
  floor: 'Floor 1',
  room: 'Main Hall',
  cabinet: '',
  network_config: { primary_ip: '10.1.1.10', hostname: 'srv-mdy-001' },
  ownership: { owned_by: 'Company Owned' },
  quantity: 1,
  reserved_quantity: 0,
  status: 'Working',
  condition: 'Used',
  lifecycle: {},
  maintenance: {},
  notes: 'Mandalay production server',
  tags: ['Production'],
  purchase_date: d(500),
  purchase_price: 12000,
  vendor: 'HP',
  warranty_expiry_date: d(60),
  created_by: 'u1',
  created_at: d(500),
  updated_at: d(30),
  updated_by: 'u1',
  is_deleted: false
},
{
  id: 'inv8',
  item_name: 'Dell PowerEdge R640',
  item_type: 'Server',
  manufacturer: 'Dell',
  model: 'PowerEdge R640',
  serial_number: 'SRV-DELL-R640-BRK',
  asset_tag: 'AT-008',
  specifications: {
    form_factor: '1U',
    cpu_model: 'Intel Xeon Silver 4210',
    cpu_count: 1,
    cores_per_cpu: 10,
    total_ram_gb: 64,
    storage_bays: 8
  },
  region_id: 'r1',
  warehouse_id: 'w1',
  rack_id: null,
  rack_position: '',
  floor: '',
  room: '',
  cabinet: '',
  network_config: {},
  ownership: { owned_by: 'Company Owned' },
  quantity: 1,
  reserved_quantity: 0,
  status: 'Broken',
  condition: 'Used',
  lifecycle: {},
  maintenance: {},
  notes: 'Motherboard failure — awaiting RMA',
  tags: ['Broken', 'RMA'],
  purchase_date: d(600),
  purchase_price: 7500,
  vendor: 'Dell Technologies',
  warranty_expiry_date: d(90),
  created_by: 'u1',
  created_at: d(600),
  updated_at: d(3),
  updated_by: 'u1',
  is_deleted: false
},
{
  id: 'inv9',
  item_name: 'Cisco Catalyst 9200-24T',
  item_type: 'Switch',
  manufacturer: 'Cisco',
  model: 'Catalyst 9200-24T',
  serial_number: 'SW-CISCO-9200-001',
  asset_tag: 'AT-009',
  specifications: {
    switch_type: 'L2 Managed',
    total_ports: 24,
    copper_ports: 24,
    sfp_plus_ports: 4,
    stackable: true
  },
  region_id: 'r2',
  warehouse_id: 'w3',
  rack_id: 'rk5',
  rack_position: 'U5',
  floor: 'Floor 1',
  room: 'Main Hall',
  cabinet: '',
  network_config: { primary_ip: '10.1.1.1', hostname: 'sw-mdy-01' },
  ownership: { owned_by: 'Company Owned' },
  quantity: 2,
  reserved_quantity: 1,
  status: 'Working',
  condition: 'New',
  lifecycle: {},
  maintenance: {},
  notes: 'Access switches for Mandalay DC',
  tags: ['Network', 'Access'],
  purchase_date: d(100),
  purchase_price: 4500,
  vendor: 'Cisco',
  warranty_expiry_date: d(-365),
  created_by: 'u1',
  created_at: d(100),
  updated_at: d(7),
  updated_by: 'u1',
  is_deleted: false
},
{
  id: 'inv10',
  item_name: 'Mikrotik CCR2004-1G-12S+2XS',
  item_type: 'Router',
  manufacturer: 'Mikrotik',
  model: 'CCR2004-1G-12S+2XS',
  serial_number: 'RTR-MK-CCR2004-001',
  asset_tag: 'AT-010',
  specifications: {
    router_type: 'Edge',
    throughput: '18 Gbps',
    sfp_slots: 12
  },
  region_id: 'r1',
  warehouse_id: 'w2',
  rack_id: 'rk4',
  rack_position: 'U1',
  floor: '',
  room: '',
  cabinet: '',
  network_config: { primary_ip: '10.0.3.1', hostname: 'rtr-hlg-01' },
  ownership: { owned_by: 'Company Owned' },
  quantity: 1,
  reserved_quantity: 0,
  status: 'Working',
  condition: 'New',
  lifecycle: {},
  maintenance: {},
  notes: '',
  tags: ['Network'],
  purchase_date: d(80),
  purchase_price: 1200,
  vendor: 'Mikrotik',
  warranty_expiry_date: d(-365),
  created_by: 'u1',
  created_at: d(80),
  updated_at: d(20),
  updated_by: 'u1',
  is_deleted: false
}];


// ---- COMPONENTS ----
export const mockComponents: Component[] = [
{
  id: 'c1',
  item_name: 'Samsung 32GB DDR4 3200MHz ECC RDIMM',
  component_type_id: 'ct1',
  manufacturer: 'Samsung',
  model: 'M393A4K40CB2-CTD',
  part_number: 'M393A4K40CB2-CTD',
  specifications: {
    memory_type: 'DDR4',
    capacity: '32GB',
    speed: '3200MHz',
    form_factor: 'RDIMM',
    ecc: true
  },
  region_id: 'r1',
  warehouse_id: 'w1',
  installed_in_device_id: null,
  device_slot: '',
  bin_location: 'Shelf-A-01',
  quantity: 24,
  reserved_quantity: 4,
  minimum_stock: 10,
  reorder_quantity: 20,
  status: 'Working',
  condition: 'New',
  tested: true,
  test_date: d(10),
  test_results: 'All modules passed memtest',
  purchase_date: d(60),
  purchase_price: 120,
  vendor: 'Samsung',
  purchase_order_number: 'PO-2024-00012',
  warranty_type: 'Manufacturer',
  warranty_expiry_date: d(-700),
  compatible_with: 'Dell PowerEdge R750, R650, R640',
  notes: '',
  tags: ['DDR4', 'ECC'],
  barcode: 'RAM-SAM-32G-001',
  created_by: 'u1',
  created_at: d(60),
  updated_at: d(5),
  updated_by: 'u1',
  is_deleted: false
},
{
  id: 'c2',
  item_name: 'Samsung 870 EVO 1TB SATA SSD',
  component_type_id: 'ct2',
  manufacturer: 'Samsung',
  model: '870 EVO',
  part_number: 'MZ-77E1T0B',
  specifications: {
    drive_type: 'SSD',
    capacity: '1TB',
    interface: 'SATA III',
    form_factor: '2.5-inch',
    read_write_speed: 'Read: 560 MB/s, Write: 530 MB/s',
    nand_type: 'TLC',
    endurance: '600 TBW'
  },
  region_id: 'r1',
  warehouse_id: 'w1',
  installed_in_device_id: null,
  device_slot: '',
  bin_location: 'Shelf-B-02',
  quantity: 15,
  reserved_quantity: 0,
  minimum_stock: 5,
  reorder_quantity: 10,
  status: 'Working',
  condition: 'New',
  tested: false,
  test_date: null,
  test_results: '',
  purchase_date: d(45),
  purchase_price: 85,
  vendor: 'Samsung',
  purchase_order_number: 'PO-2024-00015',
  warranty_type: 'Manufacturer',
  warranty_expiry_date: d(-1000),
  compatible_with: 'All servers with 2.5" bays',
  notes: '',
  tags: ['SSD', 'SATA'],
  barcode: 'SSD-SAM-1TB-001',
  created_by: 'u1',
  created_at: d(45),
  updated_at: d(8),
  updated_by: 'u1',
  is_deleted: false
},
{
  id: 'c3',
  item_name: 'Intel Xeon Gold 6348 2.6GHz',
  component_type_id: 'ct4',
  manufacturer: 'Intel',
  model: 'Xeon Gold 6348',
  part_number: 'CD8068904572204',
  specifications: {
    processor_family: 'Intel Xeon',
    generation: '3rd Gen',
    cores: 28,
    threads: 56,
    base_frequency: '2.6 GHz',
    max_turbo_frequency: '3.5 GHz',
    cache: 'L3: 42MB',
    tdp: 235,
    socket: 'LGA 4189'
  },
  region_id: 'r1',
  warehouse_id: 'w1',
  installed_in_device_id: null,
  device_slot: '',
  bin_location: 'Shelf-C-01',
  quantity: 4,
  reserved_quantity: 2,
  minimum_stock: 2,
  reorder_quantity: 4,
  status: 'Working',
  condition: 'New',
  tested: true,
  test_date: d(15),
  test_results: 'Passed stress test',
  purchase_date: d(60),
  purchase_price: 2800,
  vendor: 'Intel',
  purchase_order_number: 'PO-2024-00012',
  warranty_type: 'Manufacturer',
  warranty_expiry_date: d(-700),
  compatible_with: 'Dell PowerEdge R750',
  notes: '',
  tags: ['CPU', 'Xeon'],
  barcode: 'CPU-INT-6348-001',
  created_by: 'u1',
  created_at: d(60),
  updated_at: d(10),
  updated_by: 'u1',
  is_deleted: false
},
{
  id: 'c4',
  item_name: 'Intel X710-DA2 10GbE SFP+ NIC',
  component_type_id: 'ct5',
  manufacturer: 'Intel',
  model: 'X710-DA2',
  part_number: 'X710DA2BLK',
  specifications: {
    nic_type: 'PCIe',
    port_count: 2,
    speed: '10GbE',
    interface: 'PCIe 3.0 x8',
    port_type: 'SFP+',
    chipset: 'Intel XL710'
  },
  region_id: 'r1',
  warehouse_id: 'w1',
  installed_in_device_id: 'inv1',
  device_slot: 'PCIe Slot 2',
  bin_location: '',
  quantity: 1,
  reserved_quantity: 0,
  minimum_stock: 2,
  reorder_quantity: 4,
  status: 'Working',
  condition: 'New',
  tested: true,
  test_date: d(85),
  test_results: 'Link up, throughput verified',
  purchase_date: d(120),
  purchase_price: 350,
  vendor: 'Intel',
  purchase_order_number: '',
  warranty_type: 'Manufacturer',
  warranty_expiry_date: d(-500),
  compatible_with: 'Any server with PCIe 3.0 x8 slot',
  notes: 'Installed in srv-ygn-001',
  tags: ['NIC', '10GbE'],
  barcode: 'NIC-INT-X710-001',
  created_by: 'u1',
  created_at: d(120),
  updated_at: d(85),
  updated_by: 'u1',
  is_deleted: false
},
{
  id: 'c5',
  item_name: 'Dell 1400W Hot-Swap PSU',
  component_type_id: 'ct6',
  manufacturer: 'Dell',
  model: 'E1400E-S0',
  part_number: 'D1400E-S0',
  specifications: {
    wattage: 1400,
    efficiency: '80 Plus Platinum',
    form_factor: 'Hot-Swap',
    input_voltage: '110-240V Auto-Switching'
  },
  region_id: 'r1',
  warehouse_id: 'w1',
  installed_in_device_id: null,
  device_slot: '',
  bin_location: 'Shelf-D-01',
  quantity: 6,
  reserved_quantity: 0,
  minimum_stock: 4,
  reorder_quantity: 6,
  status: 'Working',
  condition: 'New',
  tested: false,
  test_date: null,
  test_results: '',
  purchase_date: d(60),
  purchase_price: 280,
  vendor: 'Dell Technologies',
  purchase_order_number: 'PO-2024-00012',
  warranty_type: 'Manufacturer',
  warranty_expiry_date: d(-700),
  compatible_with: 'Dell PowerEdge R750, R740',
  notes: '',
  tags: ['PSU', 'Hot-Swap'],
  barcode: 'PSU-DELL-1400-001',
  created_by: 'u1',
  created_at: d(60),
  updated_at: d(20),
  updated_by: 'u1',
  is_deleted: false
},
{
  id: 'c6',
  item_name: 'Samsung 16GB DDR4 2666MHz RDIMM',
  component_type_id: 'ct1',
  manufacturer: 'Samsung',
  model: 'M393A2K40BB2-CTD',
  part_number: 'M393A2K40BB2-CTD',
  specifications: {
    memory_type: 'DDR4',
    capacity: '16GB',
    speed: '2666MHz',
    form_factor: 'RDIMM',
    ecc: true
  },
  region_id: 'r2',
  warehouse_id: 'w3',
  installed_in_device_id: null,
  device_slot: '',
  bin_location: 'Shelf-A-01',
  quantity: 8,
  reserved_quantity: 0,
  minimum_stock: 4,
  reorder_quantity: 8,
  status: 'Working',
  condition: 'Used',
  tested: true,
  test_date: d(20),
  test_results: 'Passed',
  purchase_date: d(400),
  purchase_price: 65,
  vendor: 'Samsung',
  purchase_order_number: '',
  warranty_type: 'None',
  warranty_expiry_date: null,
  compatible_with: 'HP ProLiant DL380 Gen10',
  notes: '',
  tags: ['DDR4', 'ECC'],
  barcode: 'RAM-SAM-16G-001',
  created_by: 'u1',
  created_at: d(400),
  updated_at: d(20),
  updated_by: 'u1',
  is_deleted: false
},
{
  id: 'c7',
  item_name: 'Cat6a Network Cable 3m',
  component_type_id: 'ct10',
  manufacturer: 'Panduit',
  model: 'UTP28SP3M',
  part_number: 'UTP28SP3M',
  specifications: {
    cable_type: 'Network',
    length: '3m',
    category: 'Cat6a',
    connector_a: 'RJ45',
    connector_b: 'RJ45'
  },
  region_id: 'r1',
  warehouse_id: 'w1',
  installed_in_device_id: null,
  device_slot: '',
  bin_location: 'Shelf-E-03',
  quantity: 150,
  reserved_quantity: 0,
  minimum_stock: 50,
  reorder_quantity: 100,
  status: 'Working',
  condition: 'New',
  tested: false,
  test_date: null,
  test_results: '',
  purchase_date: d(30),
  purchase_price: 8,
  vendor: 'Panduit',
  purchase_order_number: 'PO-2024-00020',
  warranty_type: 'None',
  warranty_expiry_date: null,
  compatible_with: '',
  notes: '',
  tags: ['Cable', 'Cat6a'],
  barcode: 'CBL-PAN-CAT6A-3M',
  created_by: 'u1',
  created_at: d(30),
  updated_at: d(10),
  updated_by: 'u1',
  is_deleted: false
},
{
  id: 'c8',
  item_name: 'Cisco 10G SFP+ SR Transceiver',
  component_type_id: 'ct11',
  manufacturer: 'Cisco',
  model: 'SFP-10G-SR',
  part_number: 'SFP-10G-SR',
  specifications: {
    transceiver_type: 'SFP+',
    speed: '10G',
    wavelength: '850nm',
    connector: 'LC',
    cable_type: 'Multi-Mode',
    max_distance: '300m',
    ddm: true
  },
  region_id: 'r1',
  warehouse_id: 'w1',
  installed_in_device_id: null,
  device_slot: '',
  bin_location: 'Shelf-F-01',
  quantity: 20,
  reserved_quantity: 0,
  minimum_stock: 10,
  reorder_quantity: 20,
  status: 'Working',
  condition: 'New',
  tested: false,
  test_date: null,
  test_results: '',
  purchase_date: d(45),
  purchase_price: 45,
  vendor: 'Cisco',
  purchase_order_number: '',
  warranty_type: 'Manufacturer',
  warranty_expiry_date: d(-365),
  compatible_with: 'Cisco Catalyst 9300, 9200',
  notes: '',
  tags: ['SFP+', 'Transceiver'],
  barcode: 'SFP-CISCO-10G-001',
  created_by: 'u1',
  created_at: d(45),
  updated_at: d(15),
  updated_by: 'u1',
  is_deleted: false
}];


// ---- REQUESTS ----
export const mockInventoryRequests: InventoryRequest[] = [
{
  id: 'ir1',
  request_number: 'IR-2025-00001',
  requester_id: 'u4',
  requested_item: 'Dell PowerEdge R760',
  item_type: 'Server',
  manufacturer: 'Dell',
  model: 'PowerEdge R760',
  specifications: '2U, 2x Intel Xeon Gold 6430, 512GB DDR5, 24x NVMe bays',
  quantity: 2,
  estimated_unit_cost: 18000,
  estimated_total_cost: 36000,
  purpose: 'New production cluster expansion',
  business_justification:
  'Current capacity at 85%, need additional compute for Q2 projects',
  urgency: 'High',
  required_by: d(-30),
  budget_code: 'IT-CAPEX-2025',
  project_name: 'DC Expansion Phase 2',
  preferred_vendor: 'Dell Technologies',
  status: 'Pending',
  admin_response: '',
  reviewed_by: null,
  reviewed_at: null,
  created_at: d(5),
  updated_at: d(5)
},
{
  id: 'ir2',
  request_number: 'IR-2025-00002',
  requester_id: 'u5',
  requested_item: 'Fortinet FortiGate 200F',
  item_type: 'Firewall',
  manufacturer: 'Fortinet',
  model: 'FortiGate 200F',
  specifications: 'Next-Gen Firewall, 27 Gbps throughput, HA support',
  quantity: 1,
  estimated_unit_cost: 12000,
  estimated_total_cost: 12000,
  purpose: 'Replace aging firewall at Hlaing DC',
  business_justification: 'Current firewall EOL in 3 months',
  urgency: 'Medium',
  required_by: d(-60),
  budget_code: 'IT-CAPEX-2025',
  project_name: 'Network Refresh',
  preferred_vendor: 'Fortinet',
  status: 'Approved',
  admin_response: 'Approved. PO being created.',
  reviewed_by: 'u1',
  reviewed_at: d(2),
  created_at: d(10),
  updated_at: d(2)
},
{
  id: 'ir3',
  request_number: 'IR-2025-00003',
  requester_id: 'u6',
  requested_item: 'Cisco Catalyst 9300-24UX',
  item_type: 'Switch',
  manufacturer: 'Cisco',
  model: 'Catalyst 9300-24UX',
  specifications: '24x mGig PoE+, 4x 10G SFP+',
  quantity: 3,
  estimated_unit_cost: 6500,
  estimated_total_cost: 19500,
  purpose: 'New access layer switches for Mandalay expansion',
  business_justification:
  'New floor being added, need network infrastructure',
  urgency: 'Medium',
  required_by: d(-45),
  budget_code: 'IT-CAPEX-2025',
  project_name: 'Mandalay Expansion',
  preferred_vendor: 'Cisco',
  status: 'Rejected',
  admin_response: 'Budget not available this quarter. Resubmit in Q3.',
  reviewed_by: 'u1',
  reviewed_at: d(1),
  created_at: d(15),
  updated_at: d(1)
}];


export const mockInstallRequests: InstallRequest[] = [
{
  id: 'isr1',
  request_number: 'ISR-2025-00001',
  requester_id: 'u4',
  component_id: 'c1',
  source_warehouse_id: 'w1',
  destination_warehouse_id: 'w1',
  destination_server_id: 'inv2',
  quantity: 4,
  purpose: 'RAM upgrade for backup server — increasing from 128GB to 256GB',
  urgency: 'Medium',
  notes: 'Server will need reboot after installation',
  status: 'Pending PM Approval',
  pm_reviewed_by: null,
  pm_reviewed_at: null,
  pm_comments: '',
  admin_reviewed_by: null,
  admin_reviewed_at: null,
  admin_comments: '',
  assigned_to: 'u4',
  completed_by: null,
  completed_at: null,
  completion_notes: '',
  created_at: d(3),
  updated_at: d(3)
},
{
  id: 'isr2',
  request_number: 'ISR-2025-00002',
  requester_id: 'u4',
  component_id: 'c2',
  source_warehouse_id: 'w1',
  destination_warehouse_id: 'w1',
  destination_server_id: 'inv1',
  quantity: 2,
  purpose: 'Add storage to production server',
  urgency: 'High',
  notes: '',
  status: 'Pending Admin Approval',
  pm_reviewed_by: 'u2',
  pm_reviewed_at: d(1),
  pm_comments: 'Approved — production needs are valid',
  admin_reviewed_by: null,
  admin_reviewed_at: null,
  admin_comments: '',
  assigned_to: 'u4',
  completed_by: null,
  completed_at: null,
  completion_notes: '',
  created_at: d(7),
  updated_at: d(1)
},
{
  id: 'isr3',
  request_number: 'ISR-2025-00003',
  requester_id: 'u5',
  component_id: 'c3',
  source_warehouse_id: 'w1',
  destination_warehouse_id: 'w1',
  destination_server_id: 'inv2',
  quantity: 1,
  purpose: 'CPU upgrade for backup server',
  urgency: 'Low',
  notes: 'Scheduled for next maintenance window',
  status: 'Completed',
  pm_reviewed_by: 'u2',
  pm_reviewed_at: d(20),
  pm_comments: 'OK',
  admin_reviewed_by: 'u1',
  admin_reviewed_at: d(18),
  admin_comments: 'Approved',
  assigned_to: 'u5',
  completed_by: 'u5',
  completed_at: d(15),
  completion_notes: 'CPU installed and tested successfully',
  created_at: d(25),
  updated_at: d(15)
}];


export const mockRelocationRequests: RelocationRequest[] = [
{
  id: 'rr1',
  request_number: 'RR-2025-00001',
  requester_id: 'u4',
  relocation_type: 'INVENTORY',
  inventory_id: 'inv10',
  component_id: null,
  quantity: 1,
  source_region_id: 'r1',
  source_warehouse_id: 'w2',
  destination_region_id: 'r2',
  destination_warehouse_id: 'w3',
  destination_server_id: null,
  reason: 'Mandalay DC needs additional router',
  urgency: 'Medium',
  notes: 'Handle with care during transport',
  status: 'Pending PM Approval',
  pm_reviewed_by: null,
  pm_reviewed_at: null,
  pm_comments: '',
  admin_reviewed_by: null,
  admin_reviewed_at: null,
  admin_comments: '',
  assigned_to: 'u4',
  completed_by: null,
  completed_at: null,
  completion_notes: '',
  created_at: d(2),
  updated_at: d(2)
},
{
  id: 'rr2',
  request_number: 'RR-2025-00002',
  requester_id: 'u6',
  relocation_type: 'COMPONENT',
  inventory_id: null,
  component_id: 'c6',
  quantity: 4,
  source_region_id: 'r2',
  source_warehouse_id: 'w3',
  destination_region_id: 'r1',
  destination_warehouse_id: 'w1',
  destination_server_id: null,
  reason: 'Excess RAM at Mandalay, needed at Ahlone',
  urgency: 'Low',
  notes: '',
  status: 'Approved',
  pm_reviewed_by: 'u3',
  pm_reviewed_at: d(3),
  pm_comments: 'Approved',
  admin_reviewed_by: 'u1',
  admin_reviewed_at: d(2),
  admin_comments: 'OK to proceed',
  assigned_to: 'u6',
  completed_by: null,
  completed_at: null,
  completion_notes: '',
  created_at: d(8),
  updated_at: d(2)
}];


// ---- CUSTOMERS ----
export const mockCustomers: Customer[] = [
{
  id: 'cust1',
  customer_name: 'Myanmar Telecom Corp',
  contact_person: 'U Win Naing',
  email: 'win@mtc.com.mm',
  phone: '+95-9-111000111',
  address: 'Yangon, Myanmar',
  customer_type: 'Enterprise',
  created_at: d(200),
  updated_at: d(30)
},
{
  id: 'cust2',
  customer_name: 'Golden Tech Solutions',
  contact_person: 'Ma Thin Thin',
  email: 'thin@goldentech.mm',
  phone: '+95-9-222000222',
  address: 'Mandalay, Myanmar',
  customer_type: 'SMB',
  created_at: d(150),
  updated_at: d(45)
}];


// ---- VENDORS ----
export const mockVendors: Vendor[] = [
{
  id: 'v1',
  vendor_name: 'Dell Technologies',
  vendor_code: 'VND-001',
  contact_person: 'John Smith',
  email: 'sales@dell.com',
  phone: '+1-800-999-3355',
  address: 'Round Rock, TX, USA',
  website: 'https://dell.com',
  vendor_type: 'Manufacturer',
  payment_terms: 'Net 30',
  lead_time_days: 14,
  rating: 5,
  is_preferred: true,
  products_services: 'Servers, Storage, Networking',
  notes: '',
  is_active: true,
  created_at: d(365),
  updated_at: d(30)
},
{
  id: 'v2',
  vendor_name: 'Cisco Systems',
  vendor_code: 'VND-002',
  contact_person: 'Jane Doe',
  email: 'sales@cisco.com',
  phone: '+1-800-553-6387',
  address: 'San Jose, CA, USA',
  website: 'https://cisco.com',
  vendor_type: 'Manufacturer',
  payment_terms: 'Net 30',
  lead_time_days: 21,
  rating: 4,
  is_preferred: true,
  products_services: 'Switches, Routers, Firewalls',
  notes: '',
  is_active: true,
  created_at: d(365),
  updated_at: d(30)
},
{
  id: 'v3',
  vendor_name: 'Samsung Electronics',
  vendor_code: 'VND-003',
  contact_person: 'Kim Lee',
  email: 'b2b@samsung.com',
  phone: '+82-2-2255-0114',
  address: 'Seoul, South Korea',
  website: 'https://samsung.com',
  vendor_type: 'Manufacturer',
  payment_terms: 'Net 45',
  lead_time_days: 10,
  rating: 5,
  is_preferred: true,
  products_services: 'RAM, SSD, NVMe',
  notes: '',
  is_active: true,
  created_at: d(300),
  updated_at: d(60)
}];


// ---- AUDIT LOGS ----
export const mockAuditLogs: AuditLog[] = [
{
  id: 'al1',
  user_id: 'u1',
  action: 'CREATE',
  module: 'Inventory',
  record_id: 'inv1',
  old_value: null,
  new_value: { item_name: 'Dell PowerEdge R750' },
  ip_address: '192.168.1.100',
  timestamp: d(120)
},
{
  id: 'al2',
  user_id: 'u1',
  action: 'CREATE',
  module: 'Inventory',
  record_id: 'inv3',
  old_value: null,
  new_value: { item_name: 'Cisco Catalyst 9300-48P' },
  ip_address: '192.168.1.100',
  timestamp: d(180)
},
{
  id: 'al3',
  user_id: 'u4',
  action: 'CREATE',
  module: 'Install Request',
  record_id: 'isr1',
  old_value: null,
  new_value: { request_number: 'ISR-2025-00001' },
  ip_address: '192.168.1.50',
  timestamp: d(3)
},
{
  id: 'al4',
  user_id: 'u2',
  action: 'UPDATE',
  module: 'Install Request',
  record_id: 'isr2',
  old_value: { status: 'Pending PM Approval' },
  new_value: { status: 'Pending Admin Approval' },
  ip_address: '192.168.1.60',
  timestamp: d(1)
},
{
  id: 'al5',
  user_id: 'u1',
  action: 'UPDATE',
  module: 'Inventory',
  record_id: 'inv8',
  old_value: { status: 'Working' },
  new_value: { status: 'Broken' },
  ip_address: '192.168.1.100',
  timestamp: d(3)
},
{
  id: 'al6',
  user_id: 'u1',
  action: 'CREATE',
  module: 'Component',
  record_id: 'c1',
  old_value: null,
  new_value: {
    item_name: 'Samsung 32GB DDR4 3200MHz ECC RDIMM',
    quantity: 24
  },
  ip_address: '192.168.1.100',
  timestamp: d(60)
},
{
  id: 'al7',
  user_id: 'u4',
  action: 'CREATE',
  module: 'Relocation Request',
  record_id: 'rr1',
  old_value: null,
  new_value: { request_number: 'RR-2025-00001' },
  ip_address: '192.168.1.50',
  timestamp: d(2)
},
{
  id: 'al8',
  user_id: 'u1',
  action: 'UPDATE',
  module: 'Inventory Request',
  record_id: 'ir2',
  old_value: { status: 'Pending' },
  new_value: { status: 'Approved' },
  ip_address: '192.168.1.100',
  timestamp: d(2)
}];


// ---- NOTIFICATIONS ----
export const mockNotifications: Notification[] = [
{
  id: 'n1',
  user_id: 'u2',
  message:
  'New install request ISR-2025-00001 from Mg Kaung Myat requires your approval',
  notification_type: 'install',
  related_request_type: 'install',
  related_request_id: 'isr1',
  is_read: false,
  created_at: d(3)
},
{
  id: 'n2',
  user_id: 'u1',
  message:
  'Install request ISR-2025-00002 approved by PM and awaiting your approval',
  notification_type: 'install',
  related_request_type: 'install',
  related_request_id: 'isr2',
  is_read: false,
  created_at: d(1)
},
{
  id: 'n3',
  user_id: 'u2',
  message:
  'New relocation request RR-2025-00001 from Mg Kaung Myat requires your approval',
  notification_type: 'relocation',
  related_request_type: 'relocation',
  related_request_id: 'rr1',
  is_read: false,
  created_at: d(2)
},
{
  id: 'n4',
  user_id: 'u4',
  message: 'Your install request ISR-2025-00003 has been completed',
  notification_type: 'install',
  related_request_type: 'install',
  related_request_id: 'isr3',
  is_read: true,
  created_at: d(15)
},
{
  id: 'n5',
  user_id: 'u1',
  message:
  'Relocation request RR-2025-00002 approved by PM and awaiting your approval',
  notification_type: 'relocation',
  related_request_type: 'relocation',
  related_request_id: 'rr2',
  is_read: true,
  created_at: d(3)
}];


// ---- RESERVED STOCK ----
export const mockReservedStock: ReservedStock[] = [
{
  id: 'rs1',
  inventory_id: 'inv9',
  component_id: null,
  quantity_reserved: 1,
  reserved_for: 'Mandalay Expansion Project',
  reserved_by: 'u1',
  reservation_date: d(7),
  expected_release_date: d(-30),
  status: 'Active',
  notes: 'Reserved for new floor deployment',
  created_at: d(7),
  updated_at: d(7)
},
{
  id: 'rs2',
  inventory_id: null,
  component_id: 'c1',
  quantity_reserved: 4,
  reserved_for: 'Server RAM Upgrade — ISR-2025-00001',
  reserved_by: 'u4',
  reservation_date: d(3),
  expected_release_date: d(-14),
  status: 'Active',
  notes: 'Linked to install request',
  created_at: d(3),
  updated_at: d(3)
},
{
  id: 'rs3',
  inventory_id: null,
  component_id: 'c3',
  quantity_reserved: 2,
  reserved_for: 'Backup server CPU upgrade',
  reserved_by: 'u1',
  reservation_date: d(10),
  expected_release_date: d(-7),
  status: 'Active',
  notes: '',
  created_at: d(10),
  updated_at: d(10)
}];


// ---- MAINTENANCE TASKS ----
export const mockMaintenanceTasks: MaintenanceTask[] = [
{
  id: 'mt1',
  task_name: 'Quarterly Server Maintenance — Ahlone DC',
  description:
  'Firmware updates, health checks, and cleaning for all servers in Ahlone DC',
  inventory_id: null,
  component_id: null,
  maintenance_type: 'Preventive',
  priority: 'Medium',
  scheduled_date: d(-7),
  estimated_duration_minutes: 480,
  assigned_to: 'u4',
  recurrence: 'Quarterly',
  status: 'Scheduled',
  completion_notes: '',
  created_by: 'u1',
  created_at: d(14),
  updated_at: d(14)
},
{
  id: 'mt2',
  task_name: 'Replace failing fan in srv-ygn-002',
  description: 'Fan 3 showing high RPM alerts, needs replacement',
  inventory_id: 'inv2',
  component_id: null,
  maintenance_type: 'Corrective',
  priority: 'High',
  scheduled_date: d(-2),
  estimated_duration_minutes: 60,
  assigned_to: 'u4',
  recurrence: 'None',
  status: 'Scheduled',
  completion_notes: '',
  created_by: 'u1',
  created_at: d(5),
  updated_at: d(5)
}];


// ---- PURCHASE ORDERS ----
export const mockPurchaseOrders: PurchaseOrder[] = [
{
  id: 'po1',
  po_number: 'PO-2026-00001',
  vendor_id: 'v1',
  order_date: d(30),
  expected_delivery_date: d(-5),
  status: 'Ordered',
  line_items: [
  {
    item_name: 'Dell PowerEdge R760',
    quantity: 5,
    unit_price: 8500,
    total: 42500
  },
  {
    item_name: 'Samsung PM9A3 3.84TB NVMe',
    quantity: 20,
    unit_price: 450,
    total: 9000
  }],

  subtotal: 51500,
  tax: 5150,
  shipping_cost: 500,
  total_amount: 57150,
  payment_terms: 'Net 30',
  notes: 'Urgent order for Yangon DC expansion',
  requested_by: 'u1',
  approved_by: 'u1',
  created_at: d(30),
  updated_at: d(25)
},
{
  id: 'po2',
  po_number: 'PO-2026-00002',
  vendor_id: 'v2',
  order_date: d(15),
  expected_delivery_date: d(-10),
  status: 'Partially Received',
  line_items: [
  {
    item_name: 'Cisco Catalyst 9300',
    quantity: 10,
    unit_price: 3200,
    total: 32000
  }],

  subtotal: 32000,
  tax: 3200,
  shipping_cost: 300,
  total_amount: 35500,
  payment_terms: 'Net 45',
  notes: 'Network refresh project',
  requested_by: 'u2',
  approved_by: 'u1',
  created_at: d(15),
  updated_at: d(5)
},
{
  id: 'po3',
  po_number: 'PO-2026-00003',
  vendor_id: 'v3',
  order_date: d(5),
  expected_delivery_date: null,
  status: 'Draft',
  line_items: [
  {
    item_name: 'Palo Alto PA-5260',
    quantity: 2,
    unit_price: 45000,
    total: 90000
  }],

  subtotal: 90000,
  tax: 9000,
  shipping_cost: 0,
  total_amount: 99000,
  payment_terms: 'Net 60',
  notes: 'Firewall upgrade for Mandalay DC',
  requested_by: 'u1',
  approved_by: null,
  created_at: d(5),
  updated_at: d(5)
}];


// ---- GOODS RECEIPTS ----
export const mockGoodsReceipts: GoodsReceipt[] = [
{
  id: 'gr1',
  receipt_number: 'GR-2026-00001',
  po_id: 'po2',
  received_by: 'u4',
  received_date: d(5),
  line_items: [
  {
    item_name: 'Cisco Catalyst 9300',
    expected_qty: 10,
    received_qty: 6,
    condition: 'New',
    notes: 'Remaining 4 units on backorder'
  }],

  status: 'Partially Received',
  notes: 'Partial shipment received at Ahlone DC',
  created_at: d(5),
  updated_at: d(5)
}];


// ---- RMA RECORDS ----
export const mockRMARecords: RMARecord[] = [
{
  id: 'rma1',
  rma_number: 'RMA-2026-00001',
  vendor_id: 'v1',
  inventory_id: 'inv3',
  component_id: null,
  item_name: 'Dell PowerEdge R760 — Faulty PSU',
  reason: 'Power supply unit failed within warranty period',
  quantity: 1,
  status: 'Shipped',
  shipped_date: d(10),
  received_date: null,
  resolution: '',
  tracking_number: 'TRK-9876543210',
  created_by: 'u1',
  created_at: d(12),
  updated_at: d(10)
},
{
  id: 'rma2',
  rma_number: 'RMA-2026-00002',
  vendor_id: 'v2',
  inventory_id: null,
  component_id: 'c2',
  item_name: 'Cisco SFP-10G-SR Module — DOA',
  reason: 'Dead on arrival — no link light',
  quantity: 3,
  status: 'Resolved',
  shipped_date: d(30),
  received_date: d(20),
  resolution: 'Replacement units shipped',
  tracking_number: 'TRK-1234567890',
  created_by: 'u1',
  created_at: d(35),
  updated_at: d(15)
}];


// ---- DISPOSAL RECORDS ----
export const mockDisposalRecords: DisposalRecord[] = [
{
  id: 'disp1',
  disposal_number: 'DISP-2026-00001',
  inventory_id: 'inv5',
  component_id: null,
  item_name: 'HP ProLiant DL380 Gen8 — End of Life',
  reason: 'Hardware past end-of-life, no longer supported',
  disposal_method: 'Certified E-Waste Recycling',
  quantity: 1,
  status: 'Approved',
  approved_by: 'u1',
  disposed_date: null,
  certificate_number: '',
  notes: 'Awaiting pickup from recycling vendor',
  created_by: 'u1',
  created_at: d(7),
  updated_at: d(5)
},
{
  id: 'disp2',
  disposal_number: 'DISP-2026-00002',
  inventory_id: null,
  component_id: 'c5',
  item_name: 'Kingston DDR3 8GB — Damaged',
  reason: 'Physical damage — bent pins',
  disposal_method: 'Destruction',
  quantity: 4,
  status: 'Disposed',
  approved_by: 'u1',
  disposed_date: d(3),
  certificate_number: 'CERT-2026-0042',
  notes: 'Destroyed and documented',
  created_by: 'u4',
  created_at: d(14),
  updated_at: d(3)
}];


// ---- STOCKTAKE RECORDS ----
export const mockStocktakeRecords: StocktakeRecord[] = [
{
  id: 'st1',
  stocktake_number: 'ST-2026-00001',
  warehouse_id: 'w1',
  scheduled_date: d(-3),
  completed_date: null,
  assigned_to: 'u4',
  status: 'Planned',
  items: [
  {
    item_id: 'inv1',
    item_name: 'Dell PowerEdge R760',
    expected_qty: 10,
    actual_qty: 0,
    discrepancy: 0,
    notes: ''
  },
  {
    item_id: 'inv2',
    item_name: 'Dell PowerEdge R760',
    expected_qty: 8,
    actual_qty: 0,
    discrepancy: 0,
    notes: ''
  }],

  notes: 'Q1 2026 stocktake for Ahlone DC',
  created_by: 'u1',
  created_at: d(10),
  updated_at: d(10)
},
{
  id: 'st2',
  stocktake_number: 'ST-2026-00002',
  warehouse_id: 'w3',
  scheduled_date: d(20),
  completed_date: d(22),
  assigned_to: 'u5',
  status: 'Completed',
  items: [
  {
    item_id: 'inv4',
    item_name: 'Cisco Catalyst 9300-48P',
    expected_qty: 5,
    actual_qty: 5,
    discrepancy: 0,
    notes: 'All accounted for'
  }],

  notes: 'Mandalay DC quarterly audit — all clear',
  created_by: 'u1',
  created_at: d(25),
  updated_at: d(22)
}];